stages:
  - test
  - deploy

variables:
  APP_ENV: "production"
  APP_KEY: "base64:+c2Y1DdGUZum0HZ8j9E81AxchR2th43inHvohwxofng="
  DB_CONNECTION: "mysql"
  DB_HOST: "localhost"
  DB_DATABASE: "tp1_elequent"
  DB_USERNAME: "root"
  DB_PASSWORD: ""

before_script:
  - cp .env.example .env
  - apt-get update -qy  # Update package lists
  - apt-get install -y unzip  # Install unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer  # Install Composer globally
  - composer install --no-ansi --no-interaction --no-progress --optimize-autoloader
  - php artisan key:generate
  - php artisan migrate --force

test:
  stage: test
  script:
    - vendor/bin/phpunit

deploy:
  stage: deploy
  script:
    - echo "deploy"
