stages:
  - test
  - deploy

variables:
  MY_VARIABLE: "Hello, GitLab CI!"

before_script:
  - echo "This is a before_script step..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
